### ISSUE TITLE
How do you get this working with TF2?

### ISSUE THREAD

**Issue by JimmyCabbage** [TeamSpen210/HammerAddons#131]
I tried running this in TF2's hammer, followed all the instructions in the Wiki about getting postcompiler to work, but used TF2 directories. But when I compile, it prints out this error:
```
-------------------------------------------------------------------------------
Running command: C:\Program Files (x86)\Steam\steamapps\common\Team Fortress 2\bin\postcompiler\postcompiler.exe --propcombine "c:\program files (x86)\steam\steamapps\common\team fortress 2\tf\mapssrc/pl_toolrush"
-------------------------------------------------------------------------------

[I] postcompiler.main(): Srctools postcompiler hook started at 2021-04-20T11:47:40.166633!
[I] postcompiler.main(): Map path is c:\program files (x86)\steam\steamapps\common\team fortress 2\tf\mapssrc\pl_toolrush.bsp
[I] config.parse(): Config path: "c:\program files (x86)\steam\steamapps\common\team fortress 2\srctools.vdf"
[E] (unknown file).(unknown function)(): Uncaught Exception:
Traceback (most recent call last):
  File "srctools\scripts\postcompiler.py", line 219, in <module>
  File "srctools\scripts\postcompiler.py", line 81, in main
  File "srctools\scripts\config.py", line 85, in parse
  File "srctools\game.py", line 23, in __init__
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Program Files (x86)\\Steam\\steamapps\\common\\Team Fortress 2\\portal2\\gameinfo.txt'
[17708] Failed to execute script postcompiler
Finished. Press a key to close.
```

I tried compiling the tools on my own, but it complained about not being able to find srctools.fgd. How do I get it to work?

**Comment by Luke18033** [comment]
Check `srctools.vdf` in the game folder, it seems like the gameinfo path is set wrong

**Comment by JimmyCabbage** [comment]
thanks

**Comment by JimmyCabbage** [comment]
wait, now it's complaining about 
```
[I] postcompiler.main(): Loading soundscripts...
[E] (unknown file).(unknown function)(): Uncaught Exception:
Traceback (most recent call last):
  File "srctools\scripts\postcompiler.py", line 219, in <module>
  File "srctools\scripts\postcompiler.py", line 96, in main
  File "srctools\packlist.py", line 541, in load_soundscript_manifest
  File "srctools\packlist.py", line 446, in load_soundscript
  File "srctools\packlist.py", line 468, in _parse_soundscript
  File "srctools\sndscript.py", line 219, in parse
  File "srctools\sndscript.py", line 122, in split_float
AttributeError: 'list' object has no attribute 'upper'
```

**Comment by JimmyCabbage** [comment]
wait, is this python 3.x or 2.x?

**Comment by Luke18033** [comment]
You need at least Python 3.6.

**Comment by JimmyCabbage** [comment]
alright, I have python 3.9 so that's not the issue

**Comment by TeamSpen210** [comment]
That second error is #128, the soundscript parser code isn't handling some unique things in the scripts.

**Comment by JimmyCabbage** [comment]
ah, alright
