### ISSUE TITLE
Incompatibility with TF2 BSP version (?)

### ISSUE THREAD

**Issue by VortexParadox** [TeamSpen210/HammerAddons#146]
The VDC and this very readme states that this tool is compatible with TF2. However I could never get it to work with the game, I have seemingly exhausted all posible troubleshooting tips I can imagine, and it seems to me the tool is installed and being called correctly.
It only makes me think now that perhaps TF2's BSP vresion is not supported, specially given the error it throws:
```
[. . .]
[INFO] postcompiler.main(): Combining props...
[INFO] propcombine.combine(): Parsing QC files. Paths: 
 | C:\Program Files (x86)\Steam\steamapps\common\team fortress 2\content
 |___

[INFO] propcombine.combine(): Done! 0 props.
[INFO] propcombine.combine(): Automatically finding propcombine sets...
[ERROR] logger.except_handler(): Uncaught Exception:
Traceback (most recent call last):
  File "srctools\scripts\postcompiler.py", line 256, in <module>
  File "srctools\scripts\postcompiler.py", line 175, in main
  File "srctools\compiler\propcombine.py", line 1035, in combine
  File "srctools\bsp.py", line 450, in __get__
  File "srctools\bsp.py", line 1794, in _lmp_read_props
IndexError: list index out of range
```

**Comment by Luke18033** [comment]
See #137

**Comment by VortexParadox** [comment]
I saw this but thought it might be a different issue. Thanks
