### ISSUE TITLE
parsing config error

### ISSUE THREAD

**Issue by zeThijs** [TeamSpen210/HammerAddons#152]
When trying to use the postcompiler.exe --propcombine script the following problems occur:

1. Cannot parse config file, despite there being one in the folder it looks in. It overwrites the config file to default.

Got qc parsing to work, using default config file, but the next problem occured:
I don't know where to start with this one.

//---error log---
[I] propcombine.combine(): Done! 9334 props.
[I] propcombine.combine(): Propcombine sets present (1), combining...
[E] logger.except_handler(): Uncaught Exception:
Traceback (most recent call last):
  File "srctools\scripts\postcompiler.py", line 256, in <module>
  File "srctools\scripts\postcompiler.py", line 175, in main
  File "srctools\compiler\propcombine.py", line 1035, in combine
  File "srctools\bsp.py", line 450, in __get__
  File "srctools\bsp.py", line 1794, in _lmp_read_props
IndexError: list index out of range
[15652] Failed to execute script postcompiler
//--end error log---

//--- no longer relevant
> linked to 1. As a result, am unable to specify the qc path required. This is a problem as the default qc path is incorrectly concatenated to
<path>\nmrih\\..\content", causing critical error.

[W] config.parse(): Cannot find a valid config file! 
[W] config.parse(): Writing default to "srctools.vdf"

..

[I] propcombine.combine(): Parsing QC files. Paths:
 | E:\Games\GamesInstall\SteamLibrary\SteamApps\common\nmrih\\..\content
 |___

[I] propcombine.combine(): Done! 0 props.
[I] propcombine.combine(): Propcombine sets present (1), combining...
[E] logger.except_handler(): Uncaught Exception:
Traceback (most recent call last):
  File "srctools\scripts\postcompiler.py", line 256, in <module>
  File "srctools\scripts\postcompiler.py", line 175, in main
  File "srctools\compiler\propcombine.py", line 1035, in combine
  File "srctools\bsp.py", line 450, in __get__
  File "srctools\bsp.py", line 1794, in _lmp_read_props
IndexError: list index out of range
[7492] Failed to execute script postcompiler
//---

**Comment by zeThijs** [comment]
never mind, it doesnt work on nmrih I guess
