### ISSUE TITLE
[Dev Branch] Postcompiler crashes on combining props

### ISSUE THREAD

**Issue by WereTech** [TeamSpen210/HammerAddons#215]
This doesn't happen to the main branch's 2.5.2, but it does on the dev branch. Unsure if I'm still missing another dependency when building the postcompiler from source or if there's something else going on here. I've also noticed that it errored on trying to parse an already existing manifest from the old compiler, this may need to be checked as well.

https://pastebin.com/MBP43CVr - main log

manifest.bin error
```
[WARNING] logger.log(): Could not parse existing models file models/maps/trade_lilycove_retry1/propcombine//manifest.bin:
Traceback (most recent call last):
  File "hammeraddons\mdl_compiler.py", line 107, in __enter__
  File "<attrs generated hash hammeraddons.propcombine.PropPos>", line 13, in __hash__
    self.scale_x,
    ^^^^^^^^^^^^
AttributeError: 'PropPos' object has no attribute 'scale_x'

**Comment by TeamSpen210** [comment]
You'll need to update `srctools` to at least `2.3.9`. The manifest not being parsable is fine, it just means it needs to recompile all the props

**Comment by WereTech** [comment]
my srctools is 2.3.10 as I downloaded all the packages just prior to building the dev branch so I should have everything at its absolute latest

**Comment by WereTech** [comment]
I copied over the dist folder instead of build, however I got a different error this time. 
```
[E] logger.except_handler(): Uncaught Exception:
Traceback (most recent call last):
  File "hammeraddons\postcompiler.py", line 315, in <module>
  File "trio\_core\_run.py", line 2010, in run
  File "hammeraddons\postcompiler.py", line 201, in main
  File "hammeraddons\propcombine.py", line 1129, in combine
  File "trio\_core\_run.py", line 850, in __aexit__
  File "hammeraddons\propcombine.py", line 1124, in do_combine
  File "hammeraddons\propcombine.py", line 237, in combine_group
  File "<attrs generated hash hammeraddons.propcombine.PropPos>", line 2, in __hash__
    return hash((
           ^^^^^^
TypeError: unhashable type: 'srctools.math.Vec'
[13232] Failed to execute script 'postcompiler' due to unhandled exception!

**Comment by WereTech** [comment]
I managed to do a lot of wrong things, but have finally got it working properly after building from root with the postcompiler.spec and moving the entire dist folder over to the postcompiler folder in bin. Sorry to confuse you on all this, as again, I hadn't built a python program before so I wasn't sure what was going wrong with it in the first place. I've gotten an smd and qc in the folder to where I want it in srctools.vdc which is good that I can redefine the model path without having to hex edit. Much thanks for adding this in.
