### ISSUE TITLE
postcompiler not working

### ISSUE THREAD

**Issue by MapidsFanAnimator** [TeamSpen210/HammerAddons#223]
[E] logger.except_handler(): Uncaught Exception:
Traceback (most recent call last):
  File "hammeraddons\postcompiler.py", line 315, in <module>
  File "trio\_core\_run.py", line 2010, in run
  File "hammeraddons\postcompiler.py", line 171, in main
  File "hammeraddons\bsp_transform\__init__.py", line 167, in run_transformations
  File "D:\SteamLibrary\steamapps\common\Portal 2\bin\postcompiler\transforms\vactubes\__init__.py", line 171, in vactube_transform
    target = find_closest(
             ^^^^^^^^^^^^^
  File "D:\SteamLibrary\steamapps\common\Portal 2\bin\postcompiler\transforms\vactubes\__init__.py", line 80, in find_closest
    raise ValueError(
ValueError: No destination found for primary output of <Spline "" @ 111 -133 968, 0 0 0>! Junction at 60 -127 709.
[37160] Failed to execute script 'postcompiler' due to unhandled exception!

**Comment by TeamSpen210** [comment]
This isn't a problem with the postcompiler, as it mentions the spline junction at `60 -127 709` has nothing in front of it to output to. Check which direction is it's facing, you might need an extra node to get a straight line.
