### ISSUE TITLE
(dev) Postcompiler crashes parsing 2013 style gameinfo

### ISSUE THREAD

**Issue by vrad-exe** [TeamSpen210/HammerAddons#271]
The postcompiler on dev fails to run for 2013 engine games. It seems to now consider `+` characters to be invalid for a key name unless it is quoted, which is not how the engine behaves.
```
[E] logger.except_handler(): Uncaught Exception:
Traceback (most recent call last):
  File "hammeraddons\postcompiler.py", line 393, in <module>
  File "trio\_core\_run.py", line 2288, in run
  File "hammeraddons\postcompiler.py", line 141, in main
  File "hammeraddons\config.py", line 178, in parse
  File "srctools\game.py", line 33, in __init__
  File "srctools\keyvalues.py", line 374, in parse
srctools.keyvalues.KeyValError: Block opening ("{{") required!
```

**Comment by TeamSpen210** [comment]
This'll be fixed with the next release of `srctools`.
