### ISSUE TITLE
missing a curly bracket on line 187 in srctools tokenizer

### ISSUE THREAD

**Issue by Fennecai** [TeamSpen210/HammerAddons#43]
after decompiling all my custom content (including the entirety of models from hl2, ep1, ep2, and INFRA); using crowbar- the prop combiner doesnt work still; even with the directory set correctly to where all my qcs are now stored.

i also deleted troublesome qcs where math division was done and was mistaken as a "comment with only one slash".

even after all this debugging; i now run into the following error:

`[E] (unknown file).(unknown function)(): Uncaught Exception:
Traceback (most recent call last):
  File "F:\Git\srctools\srctools\scripts\postcompiler.py", line 123, in <module>
  File "F:\Git\srctools\srctools\scripts\postcompiler.py", line 98, in main
  File "F:\Git\srctools\srctools\compiler\propcombine.py", line 816, in combine
  File "F:\Git\srctools\srctools\compiler\propcombine.py", line 512, in load_qcs
  File "F:\Git\srctools\srctools\compiler\propcombine.py", line 617, in parse_qc
  File "srctools\_tokenizer.pyx", line 187, in srctools._tokenizer.Tokenizer.error
ValueError: Single '}' encountered in format string`

from my limited knowledge of your compiler; combined with the steps i have taken to fix the issue, I can only assume from here that this error is part of your code and not my qc files.

potentially worth noting: i do not even have an F drive

**Comment by TeamSpen210** [comment]
This is a bug in my error message meaning it won't show it to you. But the actual cause is that one of your QCs has a `$command {` or the like without the closing brace (`}`).

**Comment by TeamSpen210** [comment]
Still want to fix the crash trying to report the error.
