### ISSUE TITLE
automated packing doesnt appear to work fully

### ISSUE THREAD

**Issue by Fennecai** [TeamSpen210/HammerAddons#51]
When I compile a map with this; it packs some materials but completely misses most other custom content. To verify this; I usually do the following things after compiling a portal 2 map with this:

1. open the lump viewer in VIDE- sure enough, almost none of my custom content was packed automatically.

2. open the compiled map in my mod where the search paths don't point to a place where the content is located - indeed, the maps have missing assets everywhere.

Unless I am misunderstanding how the system works... I know that comp_pack entities can be used to force certain files to be packed; however, due to the huge amount of custom assets I'm using, this is prohibitively tedious to use for every single asset.

If indeed this works "as intended"; and I need to place those pack entities for every single asset, I would like to suggest the addition of automated packing to this, which will find all the assets automatically.

I have previously been using compile pal; but recently ran into some problems with this and compile pal crashes. I'll probably create a separate issue regarding that.

**Comment by TeamSpen210** [comment]
I do have automated packing packing support for all of these cases:

* Brush materials, static props
* FGD-based analysis of entities to retrieve any resources set in their keyvalues
* A partially complete database of the resources each entity class uses in code (so pellets pack their resources for example) 
* Parsing models to retrieve the materials used, included models, and sounds played
* Parsing materials to resolve `Patch` shaders and then textures used
* Parsing soundscripts to match the name to the script file and sounds used

So it should find almost all resources. At the start of the log, there should be a dump of all the search paths it's using - check those to see if any locations are missing? I should make it also dump the full list of resources it attempts to pack, and which search paths have been blacklisted/whitelisted for packing.

**Comment by Fennecai** [comment]
yeah; that'd be a good idea. but your right too; cause apparently it decided to work now- i think. gotta do further tests but the packing seems like its working now. i'll comment further if it doesnt

**Comment by Fennecai** [comment]
...and i loeded my mod and everything is missing. so indeed it doesnt work after all.

**Comment by Luke18033** [comment]
I think this is fixed?

**Comment by TeamSpen210** [comment]
Seems like it.

**Comment by Fennecai** [comment]
it seems that its still broken for Garry's mod though

**Comment by TeamSpen210** [comment]
In what way? I don't currently do anything for GMod, so it won't be able to automatically identify resources mounted by the `mount.kv` file. Is there a change in the BSP format then?

**Comment by Fennecai** [comment]
its broken in the way that it literally doesn't seem to pack any custom
content at all; even when it is explicitly defined in comp_pack entities

**Comment by TeamSpen210** [comment]
Can you attach the log file, after compiling?

**Comment by Fennecai** [comment]
there isn't such thing as the "mounts.kv" file in gmod (maybe there was a super long time ago but idr), gmod uses a file called ``cfg/mount.cfg`` instead.

also it appears the problem is that the postcompiler doesn't even run properly due to an error. the relevant compile log info:

```

** Executing...
** Command: E:\Antonios stuff\program files\Steam\SteamApps\common\GarrysMod\postcompiler\postcompiler.exe
** Parameters: "e:\antonios stuff\program files\steam\steamapps\common\garrysmod\sdk_content\maps/gm_fennecai_construct"

[I] postcompiler.main(): Srctools postcompiler hook started at 2021-05-11T10:59:40.026040!
[I] postcompiler.main(): Map path is e:\antonios stuff\program files\steam\steamapps\common\garrysmod\sdk_content\maps\gm_fennecai_construct.bsp
[I] config.parse(): Config path: "e:\antonios stuff\program files\steam\steamapps\common\garrysmod\srctools.vdf"
[E] (unknown file).(unknown function)(): Uncaught Exception:
Traceback (most recent call last):
  File "srctools\scripts\postcompiler.py", line 219, in <module>
  File "srctools\scripts\postcompiler.py", line 81, in main
  File "srctools\scripts\config.py", line 106, in parse
  File "pathlib.py", line 1204, in resolve
  File "pathlib.py", line 205, in resolve
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: 'E:\\Antonios stuff\\program files\\Steam\\SteamApps\\common\\GarrysMod\\garrysmod\\addons\\*'
[18716] Failed to execute script postcompiler

```

**Comment by Luke18033** [comment]
This seems to be the same problem as #26, but that's been fixed, so no idea why this would be different...

**Comment by DrPeeper228** [comment]
Still broken for portal 2

**Comment by Luke18033** [comment]
It worked for me just yesterday

**Comment by TPEcool** [comment]
When i placed `comp_pack`s into my map, all that changed is that i got a new error per `comp_pack` -
`Attempted to create unknown entity comp_pack`
`Can't init comp_pack`.
I have no idea what to do. HA also doesn't autopack those textures.

**Comment by TeamSpen210** [comment]
That suggests you're not actually running the postcompiler, it should have found and deleted those entities.

**Comment by TPEcool** [comment]
> That suggests you're not actually running the postcompiler, it should have found and deleted those entities.

Just to confirm: the postcompiler ***is*** a separate application from Hammer's map build thing?

**Comment by TPEcool** [comment]
Because i thought the default map compile thing was somehow modified by HA to autorun the postcompiler.

**Comment by TeamSpen210** [comment]
The postcompiler is an application which needs to be added to the map compile view. There is an installer that does that for you, but you probably will need to do it manually.

**Comment by TPEcool** [comment]
I did use the autoinstaller, however (please excuse my lack of proficiency in Hammer) i don't know what `map compile view` is referring to. Can you please explain?

**Comment by TeamSpen210** [comment]
I meant the "expert" compile window.

**Comment by TPEcool** [comment]
Oh, alright. I will try again when i get back home.

**Comment by TPEcool** [comment]
> That would be it yes. Those mismatched slashes might be breaking things.

Thank you, i am very new to hammeraddons so i did need some help here.
