### ISSUE TITLE
srctools.property_parser.KeyValError: Unterminated string!

### ISSUE THREAD

**Issue by Fennecai** [TeamSpen210/HammerAddons#53]
remember when the vmf was sliding into the compile and hammer said:
`C:\blah\blah\blah\SteamApps\common\Portal 2\postcompiler\postcompiler.exe`
`--nopack $path\$file`

and your compiler was like:
```
[I] postcompiler.main(): Srctools postcompiler hook started!
[I] postcompiler.main(): Map path is h:\antonios stuff\program files\steam\steamapps\common\portal 2\sdk_content\maps\pft\sp_a2_pft_stockpile_1.bsp
[I] config.parse(): Config path: "h:\antonios stuff\program files\steam\steamapps\common\portal 2\srctools.vdf"
[E] (unknown file).(unknown function)(): Uncaught Exception:
Traceback (most recent call last):
  File "F:\Git\srctools\srctools\scripts\postcompiler.py", line 132, in <module>
  File "F:\Git\srctools\srctools\scripts\postcompiler.py", line 54, in main
  File "F:\Git\srctools\srctools\scripts\config.py", line 80, in parse
  File "F:\Git\srctools\srctools\game.py", line 25, in __init__
  File "F:\Git\srctools\srctools\property_parser.py", line 279, in parse
  File "srctools\_tokenizer.pyx", line 273, in srctools._tokenizer.Tokenizer.__call__
  File "srctools\_tokenizer.pyx", line 372, in srctools._tokenizer.Tokenizer.next_token
srctools.property_parser.KeyValError: Unterminated string!
Error occurred on line 44, with file "H:\Antonios stuff\program files\Steam\SteamApps\common\Portal 2\portal2\gameinfo.txt".
[15456] Failed to execute script postcompiler
```

but then line 44 was all:
```
	"propcombine_qc_folder"	""
```

...that was great.

(sorry for the meme-ish format, its a reference to the following p1 quote because im in a comical mood right now from days straight of trying to fix problems with my mod with poor sleep. )
http://cdn.frustra.org/sounds/sound_portal1/vo/aperture_ai/escape_nags_08.mp3?id=380

**Comment by TeamSpen210** [comment]
Check the lines before that.

**Comment by Fennecai** [comment]
...done and it was fixed. sorry for the false report. :/
