### ISSUE TITLE
post compiler crashes: access denied error

### ISSUE THREAD

**Issue by Fennecai** [TeamSpen210/HammerAddons#55]
simply; the postcompiler doesnt seem to work properly on the entities, and they somehow end up in the actual engine, where errors say "Attempt to create unknown entity type comp_vactube_whatever."

as a result; the vac tube system fails, because it is functionally identical to if the system wasn't even in place.

EDIT: it turns out the postcompiler isnt even finishing it's run and crashes because "access is denied". full error:

```
[I] __init__.vactube_transform(): Compiling vactube animations ['H:\\Antonios stuff\\program files\\Steam\\SteamApps\\common\\Portal 2\\bin', '-nop4', '-i', '-game', 'H:\\Antonios stuff\\program files\\Steam\\SteamApps\\common\\Portal 2\\portal2', 'C:\\Users\\aekna\\AppData\\Local\\Temp\\vactubes_ol6ifuj4/prop.qc']...
[E] (unknown file).(unknown function)(): Uncaught Exception:
Traceback (most recent call last):
  File "F:\Git\srctools\srctools\scripts\postcompiler.py", line 132, in <module>
  File "F:\Git\srctools\srctools\scripts\postcompiler.py", line 91, in main
  File "F:\Git\srctools\srctools\bsp_transform\__init__.py", line 95, in run_transformations
  File "F:\Git\srctools\srctools\bsp_transform\vactubes\__init__.py", line 197, in vactube_transform
  File "C:\Users\Spencer Brown\AppData\Local\Programs\Python\Python36-32\lib\subprocess.py", line 403, in run
  File "C:\Users\Spencer Brown\AppData\Local\Programs\Python\Python36-32\lib\subprocess.py", line 707, in __init__
  File "C:\Users\Spencer Brown\AppData\Local\Programs\Python\Python36-32\lib\subprocess.py", line 990, in _execute_child
PermissionError: [WinError 5] Access is denied
[15100] Failed to execute script postcompiler



```
yes, i ran as admin too.

**Comment by Fennecai** [comment]
this might be related to #52 since that issue occurred shortly before this one.

**Comment by TeamSpen210** [comment]
That error is coming from when it tries to run `studiomdl`... is the path correct for that?

**Comment by TeamSpen210** [comment]
Ah, it's trying to run `Portal2/bin/` - the folder itself.

**Comment by Fennecai** [comment]
well, that's an oops. think there's any way for me to do a workaround until that is fixed? or will it be fixed pretty soon?

**Comment by TeamSpen210** [comment]
Fix the path in the config file.

**Comment by Fennecai** [comment]
...im and idiot. thanks.
